# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kotlin-web-server
  template:
    metadata:
      labels:
        app: kotlin-web-server
    spec:
      containers:
      - name: kotlin-web-server
        image: eunkyo/kotlin-web-server:latest
        ports:
        - containerPort: 8080
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kotlin-web-server-service
spec:
  selector:
    app: kotlin-web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
